name: Make and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LIBRESSL_VERSION: 3.1.3

    steps:
      - name: apt-update
        run: sudo apt-get update
      - name: install dependencies
        run: sudo apt-get -yf install automake autoconf

      - name: download libressl
        run: wget https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-${LIBRESSL_VERSION}.tar.gz
      - name: unpack libressl
        run: tar xvfz libressl-${LIBRESSL_VERSION}.tar.gz
      - name: configure libressl
        run: ./configure
        working-directory: libressl-${{env.LIBRESSL_VERSION}}
      - name: install libressl
        run: make && sudo make install && sudo ldconfig -v
        working-directory: libressl-${{env.LIBRESSL_VERSION}}

      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13'

      - name: make dumb-ws
        run: make
      - name: test dumb-ws
        run: make test
